FORMAT: 1A

# payuback

Api for PayUBack Android app

# Group User

## Login [/user/login]

### post [POST]

+ Request (application/json)

        {
            "facebookId": "168143764",
            "facebookToken": "3584asd6f81a6fg846as8d4fadga6sd8f4gsa8dfg" 
        }

+ Response 201 (application/json)

        {
            "id": 1648,
            "api-key": "16asd5f65as5d4g6afdas1df65dsafasdf"
        }
        
## default [/user]

### get [POST]

+ Request (application/json)

    + Headers
    
            api-key: "asdasdf4fd6as15f6asdf6as1dfas"

+ Response 201 (application/json)

        {
            "id": 1648,
            "email": "test@example.com",
            "name": "John Smith",
            "registeredAt": {
                "date": "2016-10-30 10:14:22.000000",
                "timezone_type": 3,
                "timezone": "Europe/Prague"
            },
            "friends": [
                {
                    "id": 243,
                    "email": "foo@example.com",
                    "name": "Will Smith"
                }, {
                    "id": 1648,
                    "email": "bar@example.com",
                    "name": "Bill Smith"
                }
            ]
        }

# Group Currencies

## Currencies [/currencies]

### default [GET]

+ Request (application/json)

    + Headers
        
            api-key: "asdasdf4fd6as15f6asdf6as1dfas"

+ Response 200 (application/json)

        {
          "currencies": [
            {
              "id": 1,
              "symbol": "Kč"
            },
            {
              "id": 2,
              "symbol": "$"
            },
            {
              "id": 3,
              "symbol": "€"
            }
          ]
        }